name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      contentful_space_id: ${{ secrets.CONTENTFUL_SPACE_ID }}
      contentful_token: ${{ secrets.CONTENTFUL_TOKEN }}

    strategy:
      matrix:
        php: ['8.1', '8.2']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: PCOV 
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: pcov

    - name: Install dependencies
      run: composer install --prefer-dist --dev
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Run Psalm
      run: ./vendor/bin/psalm --threads=2 --output-format=github --shepherd

    - name: Run Phpunit
      run: ./vendor/bin/phpunit

    - name: Run Infection
      run: ./vendor/bin/infection
